- name: backlog
  color: 7ef7ef
- name: blocked
  color: fc1423
- name: bug
  color: d73a4a
- name: caching
  color: 80c042
- name: chore
  color: ffffff
- name: ci
  color: 0075ca
- name: dependencies
  color: 0366d6
- name: discussion
  color: b6b1f9
- name: duplicate
  color: cfd3d7
- name: error handling
  color: 80c042
- name: feature request
  color: fcf95a
- name: github_actions
  color: "000000"
- name: in progress
  color: ffccd7
- name: invalid
  color: e4e669
- name: javascript
  color: "168700"
- name: leveling
  color: 80c042
- name: performance
  color: 80c042
- name: priority:high
  color: fc1423
- name: refactor
  color: 1d637f
- name: regression
  color: ea8785
- name: utility
  color: 80c042
- name: wontfix
  color: ffffff
